name = "nodejs"
entrypoint = "index.js"
extensions = [
  "js"
]
packages = [
]
setup = [
  "npm install -g jest@23.1.0 prettier@1.13.4 babylon@6.15 babel-traverse@6.21 walker@1.0.7 typescript-language-server@0.3.7 @types/node@9.6.42 typescript@3.3.3 readline-sync@1.4.9",
  "/usr/bin/build-prybar-lang.sh nodejs"
]

[run]
command = [
  "node",
  "index.js"
]

[tests]

  [tests.hello]
  code = "console.log(\"hello\")"
  output = "hello\n"
