name = "python3"
entrypoint = "main.py"
extensions = [
  "py"
]
aptRepos = [
  "ppa:deadsnakes/ppa"
]
packages = [
]
popularity = 5.0
setup = [
]
runtimeSetup = [
]

[run]
command = [
  "python3",
  "-B",
  "main.py"
]

[languageServer]
command = [
  "pyls",
  "-v"
]

[tests]

  [tests.0]
  code = "print(__name__)"
  output = "__main__\n"

  [tests.hello]
  code = "print(\"hello\")"
  output = "hello\n"

  [tests.version]
  code = "import sys; print(sys.version.startswith('3.8'))"
  output = "True\n"

  [tests.venv]
  code = "import ensurepip; print(ensurepip.version())"
  output = "19.2.3\n"
