name = "v"
entrypoint = "index.v"
extensions = [
  "v"
]
packages = [
]
setup = [
  "wget https://github.com/vlang/v/releases/download/0.1.27/v_linux.zip",
  "unzip v_linux.zip -d /opt/v",
  "ln -s /opt/v/v /usr/local/bin"
]

[run]
command = [
  "v",
  "index.v"
]